### PR TITLE
The 100% coverage test for Split management usecase.

### PR DESCRIPTION
**Pull request by laodie666**
Tests for all three split management use cases are done.

### CODE REVIEW

**Review by TorynC — APPROVED** [review]
Your test of the use case split_management looks very good and covers 100% test coverage, all test methods look useful in providing accurate tests for this use case.

**Review by andresli1219 — APPROVED** [review]
Tests for split management seem very well formatted and seems to have 100% code coverage. Very well done!

**Review by TorynC — APPROVED** [review]
This additional test for the use case split_management covers 100% test coverage and looks very good. Good job!

**Comment by lightningkoala** [comment]
Tests follow the required format, while covering all cases and providing 100% coverage. Good work.

**Review by lightningkoala — APPROVED** [review]
Tests follow the required format, while covering all cases and providing 100% coverage. Good work.

**Pull request merged**
